#!/usr/bin/env bash
#
#  Configuration sourced by other scripts.
#

export APT_PROXY="http://192.168.0.1:3142"

export RELEASE=utopic
# Read-only; files being provided *to* the container.
export RESOURCES_TMPDIR="$PWD/resources"
# Read-write; files being produced *by* the container.
export ARTIFACTS_TMPDIR="$PWD/artifacts"

export DOCKER_REPO_PATH="$PWD/../docker.git"

export CONTAINER_NAME="tmp-livessh"


export BASE_PATH="${BASE_PATH-$PWD/filesystem}"
export IMAGE_PATH="${IMAGE_PATH-$PWD/image}"
export IMAGE_NAME="ubuntukk-livessh"  # volume name of .iso
export OUTPUT_ISO_PATH="${PWD}/remix.iso"

export USERNAME=solid

#####################
## End of user-configurables
#####################

export DEBOOTSTRAP_IMAGE_TAG="$USER/ubuntu-debootstrap-minbase:$RELEASE"

