#!/usr/bin/env bash

############################################
##
############################################

$APT_GET_INSTALL nfs-common

mkdir -p /mnt/scratch

cat >>/etc/profile.d/livessh-scratch-bin.sh <<'EOF'
export PATH="/mnt/scratch/bin:${PATH}"
EOF
chmod +x /etc/profile.d/livessh-scratch-bin.sh

# N.B.: /etc/fstab (mounted at /root/etc/fstab) is overwritten by /scripts/casper-bottom/12fstab in
# the initramfs (which is /usr/share/initramfs-tools/scripts/casper-bottom/12fstab in the filesystem
# before the initramfs is built).
cat >>/usr/share/initramfs-tools/scripts/casper-bottom/70kk-nfs-mount <<'EOF'
#!/bin/sh

PREREQ=""
DESCRIPTION="Adding NFS mounts to fstab..."
FSTAB=/root/etc/fstab

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

cat >> $FSTAB <<EOF-FSTAB
192.168.0.1:/srv/nfs/scratch /mnt/scratch nfs rsize=8192,wsize=8192,timeo=14,intr,nofail,nobootwait 0 0
EOF-FSTAB

rm -f /root/etc/rcS.d/S*checkroot.sh

log_end_msg
EOF
chmod +x /usr/share/initramfs-tools/scripts/casper-bottom/70kk-nfs-mount

