#!/usr/bin/env bash

############################################
## Append entries to /etc/fstab at boot
############################################

if test -n "${LIVESSH_FSTAB_ENTRIES}"; then
    
    # N.B.: /etc/fstab (mounted at /root/etc/fstab) is overwritten by /scripts/casper-bottom/12fstab in
    # the initramfs (which is /usr/share/initramfs-tools/scripts/casper-bottom/12fstab in the filesystem
    # before the initramfs is built).
    cat >>/usr/share/initramfs-tools/scripts/casper-bottom/70livessh-fstab-entries <<'EOF'
#!/bin/sh

PREREQ=""
DESCRIPTION="Adding LiveSSH entries to fstab..."
FSTAB=/root/etc/fstab

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

cat >> $FSTAB <<EOF-FSTAB
EOF
    echo "${LIVESSH_FSTAB_ENTRIES}" >>/usr/share/initramfs-tools/scripts/casper-bottom/70livessh-fstab-entries
    cat >>/usr/share/initramfs-tools/scripts/casper-bottom/70livessh-fstab-entries <<'EOF'
EOF-FSTAB

rm -f /root/etc/rcS.d/S*checkroot.sh

log_end_msg
EOF
    chmod +x /usr/share/initramfs-tools/scripts/casper-bottom/70livessh-fstab-entries

fi
