#!/usr/bin/env bash

############################################
## Install custom software
############################################

PACKAGES=""

# XXX: Help with troubleshooting
PACKAGES+=" debconf-utils"

# TODO: Change the live user's shell.
# TODO: Get syntax coloring set up.
PACKAGES+=" zsh"

# If we tried to use $(uname -r) here, we'd get the host's kernel version, not the container's.
PACKAGES+=" linux-image-extra-virtual"

# ibstat, etc. -- should replace with Mellanox packages
PACKAGES+=" infiniband-diags"

PACKAGES+=" emacs24-nox"

$APT_GET_INSTALL $PACKAGES
