#!/usr/bin/env bash

## @KK: This doesn't do anything; I believe that the user is still not actually being created until first boot (when
## casper creates it) so trying to set a password here doesn't work.

# if test -n "$PASSWORD"; then
#    echo "$PASSWORD" | passwd --stdin "$USERNAME"
# fi
